##################################################
# file: smsclould_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.WSAServiceModuleWriter"
#      C:\Python27\Scripts\wsdl2py-script.py -a http://114.80.200.100:8081/axis2/services/smsclould?wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from smsclould_types import *
from ZSI.ServiceContainer import WSAResource

# Messages  
getStatusByTimeRequest = GED("http://yupsms.com", "getStatusByTime").pyclass

getStatusByTimeResponse = GED("http://yupsms.com", "getStatusByTimeResponse").pyclass

getStatusByIdRequest = GED("http://yupsms.com", "getStatusById").pyclass

getStatusByIdResponse = GED("http://yupsms.com", "getStatusByIdResponse").pyclass

sendsmsRequest = GED("http://yupsms.com", "sendsms").pyclass

sendsmsResponse = GED("http://yupsms.com", "sendsmsResponse").pyclass

checkBalanceRequest = GED("http://yupsms.com", "checkBalance").pyclass

checkBalanceResponse = GED("http://yupsms.com", "checkBalanceResponse").pyclass

getReplyByTimeRequest = GED("http://yupsms.com", "getReplyByTime").pyclass

getReplyByTimeResponse = GED("http://yupsms.com", "getReplyByTimeResponse").pyclass


# Service Skeletons
class smsclould(WSAResource):
    soapAction = {}
    wsAction = {}
    root = {}

    def __init__(self, post='/axis2/services/smsclould.smsclouldHttpSoap11Endpoint/', **kw):
        WSAResource.__init__(self, post)

    def wsa_getStatusByTime(self, ps, address):
        request = ps.Parse(getStatusByTimeRequest.typecode)
        return request,getStatusByTimeResponse()

    soapAction['urn:getStatusByTime'] = 'wsa_getStatusByTime'
    wsAction['wsa_getStatusByTime'] = 'urn:getStatusByTimeResponse'
    root[(getStatusByTimeRequest.typecode.nspname,getStatusByTimeRequest.typecode.pname)] = 'wsa_getStatusByTime'

    def wsa_getStatusById(self, ps, address):
        request = ps.Parse(getStatusByIdRequest.typecode)
        return request,getStatusByIdResponse()

    soapAction['urn:getStatusById'] = 'wsa_getStatusById'
    wsAction['wsa_getStatusById'] = 'urn:getStatusByIdResponse'
    root[(getStatusByIdRequest.typecode.nspname,getStatusByIdRequest.typecode.pname)] = 'wsa_getStatusById'

    def wsa_sendsms(self, ps, address):
        request = ps.Parse(sendsmsRequest.typecode)
        return request,sendsmsResponse()

    soapAction['urn:sendsms'] = 'wsa_sendsms'
    wsAction['wsa_sendsms'] = 'urn:sendsmsResponse'
    root[(sendsmsRequest.typecode.nspname,sendsmsRequest.typecode.pname)] = 'wsa_sendsms'

    def wsa_checkBalance(self, ps, address):
        request = ps.Parse(checkBalanceRequest.typecode)
        return request,checkBalanceResponse()

    soapAction['urn:checkBalance'] = 'wsa_checkBalance'
    wsAction['wsa_checkBalance'] = 'urn:checkBalanceResponse'
    root[(checkBalanceRequest.typecode.nspname,checkBalanceRequest.typecode.pname)] = 'wsa_checkBalance'

    def wsa_getReplyByTime(self, ps, address):
        request = ps.Parse(getReplyByTimeRequest.typecode)
        return request,getReplyByTimeResponse()

    soapAction['urn:getReplyByTime'] = 'wsa_getReplyByTime'
    wsAction['wsa_getReplyByTime'] = 'urn:getReplyByTimeResponse'
    root[(getReplyByTimeRequest.typecode.nspname,getReplyByTimeRequest.typecode.pname)] = 'wsa_getReplyByTime'

